package drivers

// generate writes generated.go from the lists of the indi build. A
// list is one file in indi/images/ for each image, named for the
// image's family: zwo is the image indi-zwo. Each line "driver <name>"
// puts one driver in that image. The list named unpublished holds the
// drivers that no image holds, and the lists named indi and simulators
// hold whole packages and files, and no driver line.

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// unpublishedList names the list of drivers that no image holds.
const unpublishedList = "unpublished"

func generate(imagesDir, packageToml string) ([]byte, error) {
	tag, err := pinnedTag(packageToml)
	if err != nil {
		return nil, err
	}
	lists, err := os.ReadDir(imagesDir)
	if err != nil {
		return nil, err
	}
	families := map[string]string{}
	for _, list := range lists {
		drivers, err := listedDrivers(filepath.Join(imagesDir, list.Name()))
		if err != nil {
			return nil, err
		}
		family := list.Name()
		if family == unpublishedList {
			family = ""
		}
		for _, driver := range drivers {
			if other, seen := families[driver]; seen {
				return nil, fmt.Errorf("%s is in the lists %q and %q", driver, other, list.Name())
			}
			families[driver] = family
		}
	}
	names := make([]string, 0, len(families))
	for name := range families {
		names = append(names, name)
	}
	slices.Sort(names)

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by TestTheMapIsCurrent -update from indi/images/ and indi/package.toml; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package drivers\n\n")
	fmt.Fprintf(&out, "// Tag is the tag of the indi images, <version>-<revision> from indi/package.toml.\n")
	fmt.Fprintf(&out, "const Tag = %q\n\n", tag)
	fmt.Fprintf(&out, "// families maps each third-party driver to the family of the image\n")
	fmt.Fprintf(&out, "// that holds it, and to \"\" when no image holds it.\n")
	fmt.Fprintf(&out, "var families = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(&out, "\t%q: %q,\n", name, families[name])
	}
	fmt.Fprintf(&out, "}\n")
	return format.Source(out.Bytes())
}

// listedDrivers reads the driver lines of one list.
func listedDrivers(path string) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	var drivers []string
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) == 2 && fields[0] == "driver" {
			drivers = append(drivers, fields[1])
		}
	}
	return drivers, scanner.Err()
}

// pinnedTag reads <version>-<revision> from the [package] table of
// indi/package.toml, the tag that CI publishes the images under.
func pinnedTag(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		key, value, ok := strings.Cut(scanner.Text(), "=")
		key = strings.TrimSpace(key)
		if _, seen := values[key]; ok && !seen {
			values[key] = strings.Trim(strings.TrimSpace(value), `"`)
		}
	}
	if values["version"] == "" || values["revision"] == "" {
		return "", fmt.Errorf("%s names no version and revision", path)
	}
	return values["version"] + "-" + values["revision"], scanner.Err()
}
