package main

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// The document is generated from the route table, so no route can
// be served and undescribed.
func TestEveryRouteIsInTheOpenAPIDocument(t *testing.T) {
	document := openAPIDocument(openAPIPlaceholderServer)
	paths, held := document["paths"].(map[string]any)
	if !held {
		t.Fatal("the document holds no paths object")
	}
	if len(paths) != len(apiRoutes) {
		t.Errorf("the document describes %d paths and the router serves %d", len(paths), len(apiRoutes))
	}
	for _, route := range apiRoutes {
		item, described := paths[route.template].(map[string]any)
		if !described {
			t.Fatalf("the document describes no path item for %s", route.template)
		}
		for _, method := range []string{"get", "head", "options"} {
			if _, answered := item[method]; !answered {
				t.Errorf("%s describes no %s operation", route.template, method)
			}
		}
	}
}

// An extension form is its own path item, because OpenAPI 3.1 has
// no {.ext} expansion.
func TestTheDocumentEnumeratesTheExtensionPaths(t *testing.T) {
	paths := openAPIDocument(openAPIPlaceholderServer)["paths"].(map[string]any)
	for _, form := range screenForms {
		template := apiRoot + "/" + displaysPlural + "/{name}/" + screenAspect + "." + form.ext
		if _, described := paths[template]; !described {
			t.Errorf("the document describes no path item for %s", template)
		}
	}
}

// The served copy carries the base it was asked for; the committed
// copy carries the placeholder.
func TestTheServedDocumentCarriesItsServer(t *testing.T) {
	servers := openAPIDocument("https://display.example")["servers"].([]any)
	if got := servers[0].(map[string]any)["url"]; got != "https://display.example" {
		t.Errorf("the served copy names %v, want the base it was given", got)
	}
}

// The manual's copy is the generator's own output, so a route added
// here reaches the page it is read on.
func TestTheCommittedDocumentIsTheGeneratorsOwn(t *testing.T) {
	committed, err := os.ReadFile("docs/content/docs/reference/openapi.json")
	if err != nil {
		t.Fatal(err)
	}
	var held, rendered map[string]any
	if err := json.Unmarshal(committed, &held); err != nil {
		t.Fatal(err)
	}
	fresh, err := renderJSON(openAPIDocument(openAPIPlaceholderServer))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(fresh, &rendered); err != nil {
		t.Fatal(err)
	}
	// The copies differ on two members: the base the request answers
	// on and the release the process was built as. The committed copy
	// is generated by a development build, so both are ignored.
	for _, document := range []map[string]any{held, rendered} {
		delete(document, "servers")
		delete(document["info"].(map[string]any), "version")
	}
	if !reflect.DeepEqual(held, rendered) {
		t.Error("the committed OpenAPI document is not what this build renders; run make -C docs build")
	}
}

// The discovery document is the shape the three capture APIs share,
// member for member.
func TestTheDiscoveryDocumentIsTheSharedShape(t *testing.T) {
	document := discovery()
	screens, held := document.Resources[displaysPlural]
	if !held {
		t.Fatalf("the document lists %v, want the displays resource", document.Resources)
	}
	if screens.Self != apiRoot+"/displays/{name}" {
		t.Errorf("self is %q", screens.Self)
	}
	aspect, described := screens.Aspects[screenAspect]
	if !described {
		t.Fatalf("the resource lists %v, want the screen aspect", screens.Aspects)
	}
	if aspect.Template != screenTemplate {
		t.Errorf("the template is %q, want %q", aspect.Template, screenTemplate)
	}
	if !reflect.DeepEqual(aspect.MediaTypes, screenMediaTypes()) {
		t.Errorf("the types are %v, want %v", aspect.MediaTypes, screenMediaTypes())
	}
	if !reflect.DeepEqual(aspect.Extensions, []string{"png", "jpg", "mp4", "mjpeg"}) {
		t.Errorf("the extensions are %v", aspect.Extensions)
	}
	if aspect.Redirects {
		t.Error("the screen aspect redirects, and a Display is the thing itself")
	}
	if document.OpenAPI != apiRoot+"/openapi.json" {
		t.Errorf("the document names %q as its description", document.OpenAPI)
	}
}
