package main

import (
	"encoding/json"
	"io"
	"net/http"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/liken-sh/liken/cluster"
	"golang.org/x/crypto/ssh"
)

func fluxCluster() *cluster.Cluster {
	c := &cluster.Cluster{}
	c.Metadata.Name = "lab"
	c.Spec.Features = map[string]*cluster.FeatureConfig{
		"flux": {
			"repository": "ssh://git@forge.example/fleet.git",
			"knownHosts": "forge.example ssh-ed25519 HOSTKEY",
		},
	}
	return c
}

// The minted pair must round-trip through the same library Flux's
// git client uses to read it, and the two halves must agree.
func TestMintDeployKeyProducesAMatchedPair(t *testing.T) {
	pub, priv, err := mintDeployKey("lab")
	if err != nil {
		t.Fatal(err)
	}
	parsedPub, comment, _, _, err := ssh.ParseAuthorizedKey([]byte(pub))
	if err != nil {
		t.Fatalf("the public half must parse as an authorized_keys line: %v", err)
	}
	if comment != "liken:lab" {
		t.Errorf("the comment should name the cluster, got %q", comment)
	}
	signer, err := ssh.ParsePrivateKey([]byte(priv))
	if err != nil {
		t.Fatalf("the private half must parse as an SSH private key: %v", err)
	}
	if string(signer.PublicKey().Marshal()) != string(parsedPub.Marshal()) {
		t.Error("the two halves must be the same key")
	}
}

func TestEnsureFluxDeployKeyDoesNothingWithoutTheFeature(t *testing.T) {
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		t.Errorf("no API call should happen: %s %s", r.Method, r.URL.Path)
	}))
	plain := &cluster.Cluster{}
	plain.Metadata.Name = "lab"
	if got := ensureFluxDeployKey(c, plain); got != "" {
		t.Errorf("no feature, no key: got %q", got)
	}
}

func TestEnsureFluxDeployKeyReadsAnExistingKey(t *testing.T) {
	// data values arrive base64-encoded from the API: the public key
	// line, and the known_hosts value that already matches the
	// declared one, so no write of any kind should happen.
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("an existing, current key must only be read: %s %s", r.Method, r.URL.Path)
		}
		w.Write([]byte(`{"type": "Opaque", "data": {
			"identity.pub": "c3NoLWVkMjU1MTkgQUFBQSBsaWtlbjpsYWI=",
			"known_hosts": "Zm9yZ2UuZXhhbXBsZSBzc2gtZWQyNTUxOSBIT1NUS0VZ"}}`))
	}))
	got := ensureFluxDeployKey(c, fluxCluster())
	if got != "ssh-ed25519 AAAA liken:lab" {
		t.Errorf("got %q", got)
	}
}

// The declared knownHosts can change after the mint: a forge rotates
// its host key, or the first declaration was wrong. The key itself
// never changes here, but the Secret's known_hosts entry follows the
// declaration.
func TestEnsureFluxDeployKeyRefreshesStaleKnownHosts(t *testing.T) {
	var patched string
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			w.Write([]byte(`{"type": "Opaque", "data": {
				"identity.pub": "c3NoLWVkMjU1MTkgQUFBQSBsaWtlbjpsYWI=",
				"known_hosts": "b2xk"}}`))
		case http.MethodPatch:
			body, _ := io.ReadAll(r.Body)
			patched = string(body)
		default:
			t.Errorf("unexpected call: %s %s", r.Method, r.URL.Path)
		}
	}))
	if got := ensureFluxDeployKey(c, fluxCluster()); got != "ssh-ed25519 AAAA liken:lab" {
		t.Errorf("got %q", got)
	}
	if !strings.Contains(patched, "forge.example ssh-ed25519 HOSTKEY") {
		t.Errorf("the patch should carry the declared known_hosts, got %q", patched)
	}
}

func TestEnsureFluxDeployKeyMintsIntoTheSecret(t *testing.T) {
	var created struct {
		Metadata struct {
			Name      string `json:"name"`
			Namespace string `json:"namespace"`
		} `json:"metadata"`
		StringData map[string]string `json:"stringData"`
	}
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			http.NotFound(w, r)
		case http.MethodPost:
			if err := json.NewDecoder(r.Body).Decode(&created); err != nil {
				t.Fatal(err)
			}
			w.WriteHeader(http.StatusCreated)
		}
	}))
	got := ensureFluxDeployKey(c, fluxCluster())
	if created.Metadata.Name != "flux-system" || created.Metadata.Namespace != "flux-system" {
		t.Errorf("the Secret must use Flux's conventional name: %+v", created.Metadata)
	}
	if !strings.HasPrefix(created.StringData["identity"], "-----BEGIN OPENSSH PRIVATE KEY-----") {
		t.Errorf("identity must carry the private half: %q", created.StringData["identity"])
	}
	if !strings.HasPrefix(created.StringData["identity.pub"], "ssh-ed25519 ") {
		t.Errorf("identity.pub must carry the public half: %q", created.StringData["identity.pub"])
	}
	if created.StringData["known_hosts"] != "forge.example ssh-ed25519 HOSTKEY" {
		t.Errorf("known_hosts must carry the declared host keys: %q", created.StringData["known_hosts"])
	}
	if got != created.StringData["identity.pub"] {
		t.Errorf("the returned key must be the minted one: %q vs %q", got, created.StringData["identity.pub"])
	}
}

const testSeed = `---
# This manifest was generated by flux. DO NOT EDIT.
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gitrepositories.source.toolkit.fluxcd.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
`

func TestParseSeedReadsEveryDocument(t *testing.T) {
	objects, err := parseSeed([]byte(testSeed))
	if err != nil {
		t.Fatal(err)
	}
	if len(objects) != 3 {
		t.Fatalf("expected three objects, got %d", len(objects))
	}
	if objects[0].Kind != "Namespace" || objects[0].Name != "flux-system" {
		t.Errorf("first object: %+v", objects[0])
	}
	if objects[2].Namespace != "flux-system" {
		t.Errorf("the Deployment must keep its namespace: %+v", objects[2])
	}
}

func TestSeedCollectionPaths(t *testing.T) {
	for _, tc := range []struct {
		apiVersion, kind, namespace, want string
	}{
		{"v1", "Namespace", "", "/api/v1/namespaces"},
		{"v1", "ServiceAccount", "flux-system", "/api/v1/namespaces/flux-system/serviceaccounts"},
		{"apps/v1", "Deployment", "flux-system", "/apis/apps/v1/namespaces/flux-system/deployments"},
		{"apiextensions.k8s.io/v1", "CustomResourceDefinition", "", "/apis/apiextensions.k8s.io/v1/customresourcedefinitions"},
		{"rbac.authorization.k8s.io/v1", "ClusterRoleBinding", "", "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings"},
		{"networking.k8s.io/v1", "NetworkPolicy", "flux-system", "/apis/networking.k8s.io/v1/namespaces/flux-system/networkpolicies"},
	} {
		got, err := collectionPath(seedObject{APIVersion: tc.apiVersion, Kind: tc.kind, Namespace: tc.namespace})
		if err != nil {
			t.Errorf("%s: %v", tc.kind, err)
		}
		if got != tc.want {
			t.Errorf("%s: got %q, want %q", tc.kind, got, tc.want)
		}
	}
	if _, err := collectionPath(seedObject{APIVersion: "v1", Kind: "Pod"}); err == nil {
		t.Error("a kind outside the seed's vocabulary must be an error")
	}
}

// When the build has copied the real seed (make always does), every
// one of its documents must parse and map in the planter's table,
// and the probe object must be among them. This is the test that
// fails when a Flux version bump introduces a kind the table does
// not know. A checkout that has not fetched the flux domain skips,
// because the embed then holds only the README.
func TestTheRealSeedParsesAndMapsWhole(t *testing.T) {
	seed, err := engineSeed()
	if err != nil {
		t.Skip("no seed copied yet; the Makefile supplies it")
	}
	objects, err := parseSeed(seed)
	if err != nil {
		t.Fatal(err)
	}
	probeSeen := false
	for _, o := range objects {
		if _, err := collectionPath(o); err != nil {
			t.Error(err)
		}
		if o.Kind == "Deployment" && o.Name == "kustomize-controller" {
			probeSeen = true
		}
	}
	if !probeSeen {
		t.Error("the seed must contain the probe object, the kustomize-controller Deployment")
	}
}

func TestEnsureFluxEngineLeavesAPresentEngineAlone(t *testing.T) {
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			t.Errorf("a present engine is git's, never re-planted: %s %s", r.Method, r.URL.Path)
		}
		w.Write([]byte(`{"metadata": {"name": "kustomize-controller"}}`))
	}))
	ensureFluxEngine(c, fluxCluster(), []byte(testSeed))
}

func TestEnsureFluxEnginePlantsWhenAbsent(t *testing.T) {
	var created []string
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			http.NotFound(w, r)
		case http.MethodPost:
			created = append(created, r.URL.Path)
			// The namespace already exists (liken owns it); the
			// planter must shrug and continue.
			if r.URL.Path == "/api/v1/namespaces" {
				w.WriteHeader(http.StatusConflict)
				return
			}
			w.WriteHeader(http.StatusCreated)
		}
	}))
	ensureFluxEngine(c, fluxCluster(), []byte(testSeed))
	want := []string{
		"/api/v1/namespaces",
		"/apis/apiextensions.k8s.io/v1/customresourcedefinitions",
		"/apis/apps/v1/namespaces/flux-system/deployments",
	}
	if !slices.Equal(created, want) {
		t.Errorf("created %v, want %v", created, want)
	}
}

func TestEnsureFluxEngineDoesNothingWithoutTheFeature(t *testing.T) {
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		t.Errorf("no API call should happen: %s %s", r.Method, r.URL.Path)
	}))
	plain := &cluster.Cluster{}
	plain.Metadata.Name = "lab"
	ensureFluxEngine(c, plain, []byte(testSeed))
}

// A conflicting create means another leader's operator minted first.
// The sweep returns nothing this pass and reads the winner's key on
// the next one; both copies then publish the same value.
func TestEnsureFluxDeployKeyYieldsToAConcurrentMint(t *testing.T) {
	c := testClient(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			http.NotFound(w, r)
		case http.MethodPost:
			w.WriteHeader(http.StatusConflict)
			w.Write([]byte(`{"kind": "Status", "reason": "AlreadyExists"}`))
		}
	}))
	if got := ensureFluxDeployKey(c, fluxCluster()); got != "" {
		t.Errorf("a lost race publishes nothing this pass: got %q", got)
	}
}

// Retraction's other half of the seed contract: every cluster-scoped
// object the seed creates must be on the janitor's teardown list,
// and the operator's standing rights must name it. A Flux version
// bump that adds a CRD fails here until both keep up. Namespaced
// objects need no entry: the namespace's own deletion sweeps them.
func TestTheTeardownAndItsRightsCoverTheSeed(t *testing.T) {
	seed, err := engineSeed()
	if err != nil {
		t.Skip("no seed copied yet; the Makefile supplies it")
	}
	objects, err := parseSeed(seed)
	if err != nil {
		t.Fatal(err)
	}
	rights, err := os.ReadFile("manifests/cluster-operator.yaml")
	if err != nil {
		t.Fatal(err)
	}
	for _, o := range objects {
		var path string
		switch o.Kind {
		case "CustomResourceDefinition":
			path = "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/" + o.Name
		case "ClusterRole":
			path = "/apis/rbac.authorization.k8s.io/v1/clusterroles/" + o.Name
		case "ClusterRoleBinding":
			path = "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/" + o.Name
		default:
			continue
		}
		if !slices.Contains(fluxTeardownPaths, path) {
			t.Errorf("the teardown must cover %s %s", o.Kind, o.Name)
		}
		if !strings.Contains(string(rights), o.Name) {
			t.Errorf("the operator's standing rights must name %s %s", o.Kind, o.Name)
		}
	}
}
