package main

// A Kubernetes API client from first principles.
//
// Every pod starts with everything it needs to reach the API server.
// Kubernetes injects two environment variables naming the server's
// in-cluster address, and kubelet mounts a directory of credentials
// into every container at a well-known path: a CA certificate to
// verify the server, and a ServiceAccount token to authenticate as.
// "In-cluster config", the thing client-go's rest.InClusterConfig()
// does, is nothing more than reading those five values.
//
// From there the API is plain REST. Every object lives at a predictable
// URL (/apis/<group>/<version>/<plural>/<name>), GET reads it, POST
// creates it, PUT replaces it, and authentication is one bearer-token
// header. kubectl -v=9 prints these exact requests; this file makes
// the same requests directly.

import (
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/rand/v2"
	"net/http"
	"os"
	"time"

	"github.com/chrisguidry/liken/machine"
)

const serviceAccountDir = "/var/run/secrets/kubernetes.io/serviceaccount"

// machinesPath and clustersPath are where our CRDs' objects live. The
// URL structure is the same for every resource in Kubernetes:
// built-ins just use the legacy /api/v1 root instead of
// /apis/<group>. Both kinds are cluster-scoped, so there's no
// /namespaces/<ns>/ segment.
const (
	machinesPath = "/apis/" + machine.APIVersion + "/machines"
	clustersPath = "/apis/" + machine.APIVersion + "/clusters"
)

type apiClient struct {
	base string
	http *http.Client

	// credentials is the directory holding the ServiceAccount token.
	// It is a field rather than the constant above so that tests can
	// point the client at a directory they control.
	credentials string
}

func inClusterClient() (*apiClient, error) {
	host, port := os.Getenv("KUBERNETES_SERVICE_HOST"), os.Getenv("KUBERNETES_SERVICE_PORT")
	if host == "" || port == "" {
		return nil, fmt.Errorf("not running in a cluster: KUBERNETES_SERVICE_HOST unset")
	}

	// The mounted CA is the cluster's server CA: the same root
	// generated by identity/mint.sh before this machine ever booted.
	// Trusting exactly that CA, not the system trust store, means the
	// client only accepts the cluster's own API server and rejects
	// anything else answering on that address.
	caPEM, err := os.ReadFile(serviceAccountDir + "/ca.crt")
	if err != nil {
		return nil, fmt.Errorf("reading service account CA: %w", err)
	}
	roots := x509.NewCertPool()
	if !roots.AppendCertsFromPEM(caPEM) {
		return nil, fmt.Errorf("service account CA contains no certificates")
	}

	return &apiClient{
		base: "https://" + host + ":" + port,
		http: &http.Client{
			Transport: &http.Transport{
				TLSClientConfig: &tls.Config{RootCAs: roots},
				// Watches are long-lived responses that deliver data a
				// little at a time, and the server ends them on its own
				// schedule. A whole-request client timeout would cut
				// every watch off mid-stream, so only the response
				// headers get a deadline.
				ResponseHeaderTimeout: 30 * time.Second,
				// A pooled connection that has sat idle is the one most
				// likely to be silently dead: the server may have closed
				// it, or the network path may have quietly reset. Go
				// writes the next request onto it anyway and only learns
				// the truth when no answer comes; the server sees an
				// orphaned request from a client that already gave up
				// and logs it as an abort. Discarding idle connections
				// after a short sit means the next request dials fresh
				// instead of gambling on a stale socket. The operator's
				// steady cadence keeps its one working connection busier
				// than this, so the timeout only ever reaps the strays
				// opened during bursts.
				IdleConnTimeout: 30 * time.Second,
			},
		},
		credentials: serviceAccountDir,
	}, nil
}

// do issues one authenticated request. The token is re-read from disk
// every time: ServiceAccount tokens are short-lived now (kubelet
// refreshes the mounted file as they approach expiry), and a client
// that caches one in memory eventually starts getting 401s.
func (c *apiClient) do(method, path, contentType string, body []byte) (*http.Response, error) {
	token, err := os.ReadFile(c.credentials + "/token")
	if err != nil {
		return nil, fmt.Errorf("reading service account token: %w", err)
	}
	var reader io.Reader
	if body != nil {
		reader = bytes.NewReader(body)
	}
	req, err := http.NewRequest(method, c.base+path, reader)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+string(token))
	req.Header.Set("Accept", "application/json")
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	return c.http.Do(req)
}

// retryPause sleeps about five seconds, randomized upward by as much
// as half again. The jitter matters because a fleet reboots together:
// every machine's operator hits the same not-served-yet CRDs and
// dropped watches at the same moments, and identical retry delays
// would keep them all retrying in unison. Randomizing the delay
// spreads that load out. It is a variable so tests can replace it
// with a no-op, the same seam init's disk code leaves with sysBlock
// and devRoot.
var retryPause = func() {
	base := 5 * time.Second
	time.Sleep(base + rand.N(base/2))
}

// errNotFound distinguishes "this object doesn't exist" from real
// failures: an absent object is an ordinary state, and the caller
// handles it by creating the object. errConflict does the same for
// "something else wrote first", which is an ordinary state under
// optimistic concurrency, handled by re-reading.
var (
	errNotFound = errors.New("not found")
	errConflict = errors.New("conflict: something else wrote this object first")
)

// patchJSON applies a JSON merge patch (RFC 7386): send only the
// fields to change, and the server merges them into the object (a
// null value deletes a key). This deliberately sidesteps optimistic
// concurrency: a merge patch carries no resourceVersion, so it can't
// conflict. That is the right tool when the caller owns the specific
// fields it's touching, such as a cordon flag or an annotation, and
// doesn't care what the rest of the object looks like.
func (c *apiClient) patchJSON(path string, patch []byte) error {
	resp, err := c.do(http.MethodPatch, path, "application/merge-patch+json", patch)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		message, _ := io.ReadAll(io.LimitReader(resp.Body, 2048))
		return fmt.Errorf("PATCH %s: %s: %s", path, resp.Status, message)
	}
	return nil
}

// requestJSON runs a request and decodes the JSON response into out,
// turning non-2xx statuses into errors that include the server's
// response body. Kubernetes API errors are structured JSON with a
// message field, but the raw body is readable enough for our
// purposes.
func (c *apiClient) requestJSON(method, path string, body []byte, out any) error {
	contentType := ""
	if body != nil {
		contentType = "application/json"
	}
	resp, err := c.do(method, path, contentType, body)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return errNotFound
	}
	if resp.StatusCode == http.StatusConflict {
		return errConflict
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		message, _ := io.ReadAll(io.LimitReader(resp.Body, 2048))
		return fmt.Errorf("%s %s: %s: %s", method, path, resp.Status, message)
	}
	if out == nil {
		return nil
	}
	return json.NewDecoder(resp.Body).Decode(out)
}
