#!/usr/bin/env bash
#
# Assemble the liken image: an initramfs the kernel unpacks into RAM.
#
# This directory is organized as a mirror of the filesystem it
# produces: image/etc/rancher/k3s/config.yaml is the file the machine
# sees at /etc/rancher/k3s/config.yaml, and so on: configuration lives
# at its destination path, reviewable with plain ls. The build stages
# that tree plus the built and vendored artifacts in dist/root, then
# archives it with cpio. The complete inventory of the operating
# system:
#
#   /liken                        init; the kernel runs it as PID 1
#                                 (rdinit=/liken)
#   /etc/liken/cluster.yaml       what the machines form together: the
#                                 cluster's topology and address plan
#   /etc/liken/machines/          one Machine manifest per machine; a
#                                 boot selects its own by the
#                                 liken.machine=<name> kernel parameter,
#                                 which is how one image boots a fleet.
#                                 The manifests (and cluster.yaml) are
#                                 an *input* to this build, not part of
#                                 this domain: which machines exist and
#                                 what they form is a deployment's
#                                 decision, so the caller points the
#                                 build at a directory carrying them
#                                 (the repo's own lab is dev-cluster/)
#   /etc/liken/token              the cluster's join token, minted
#                                 offline by identity/mint.sh: it
#                                 embeds a hash of the server CA below,
#                                 so a joining machine can verify the
#                                 cluster before presenting the secret
#   /etc/liken/modules.conf       which kernel modules init loads
#   /lib/modules/<release>/       those modules and their dependencies,
#                                 exactly as Ubuntu built them
#   /bin/k3s                      all of Kubernetes, in one binary
#   /etc/rancher/k3s/config.yaml  k3s's server-role configuration
#   /etc/rancher/k3s/agent.yaml   k3s's agent-role configuration (init
#                                 starts the role the cluster manifest
#                                 implies, and each role reads its own
#                                 file plus a boot-derived drop-in)
#   /sbin/iptables (& friends)    the netfilter userspace kube-proxy and
#                                 the CNI exec to program the kernel's
#                                 packet filter: one static multi-call
#                                 binary (vendored from k3s-root by
#                                 xtables/fetch.sh) under each of the
#                                 names it answers to. k3s puts /sbin
#                                 ahead of its own bundled tools on the
#                                 PATHs it builds, so these win, which
#                                 matters because the bundled iptables
#                                 is a #!/bin/sh script, and there is no
#                                 shell here to run it
#   /sbin/mke2fs                  makes ext4 filesystems on the disks
#                                 init claims; static, vendored from
#                                 gokrazy's reproducible e2fsprogs build
#                                 (see e2fsprogs/fetch.sh). It carries
#                                 its own built-in default profile, so
#                                 no mke2fs.conf ships
#   /etc/ssl/certs/               CA certificates (vendored by the trust
#                                 domain), so pulling images over TLS
#                                 can verify who it's talking to
#   /etc/passwd, group,           the Unix identity files: this machine
#     subuid, subgid              has exactly two users, root and nobody,
#                                 and no way to log in as either. kubelet
#                                 reads passwd and the sub-ID ranges to
#                                 map container users into namespaces
#   /var/lib/rancher/k3s/         the cluster's certificate authorities,
#     server/tls/                 generated by the identity domain. k3s
#                                 finds them here and signs its leaf
#                                 certs from them instead of inventing
#                                 its own roots, which is what makes an
#                                 operator's kubeconfig computable
#                                 offline (identity/mint.sh). It also
#                                 means the image contains private keys:
#                                 whoever holds this file owns the
#                                 cluster it boots
#   /var/lib/rancher/k3s/         the Machine CRD and the liken operator's
#     server/manifests/           deployment: k3s applies everything in
#                                 this directory to the cluster at
#                                 startup, so the OS's own resources
#                                 arrive with no kubectl step
#   /var/lib/rancher/k3s/         the liken operator's container image as
#     agent/images/               an OCI tarball (built by hand in
#                                 operator/image.sh); k3s imports every
#                                 archive here into containerd at start,
#                                 so the machine never pulls its own OS
#                                 components from a registry
#
# Nothing else. No shell, no coreutils, no libc: every file above is
# either written in this repo or vendored by a pinned, verified fetch.

set -euo pipefail

# Where the Machine and Cluster manifests come from: the build's one
# argument. Omitted, the image carries no manifests at all, which is
# still a valid machine (everything defaults, DHCP and RAM root) —
# the deployment decided nothing, so nothing is baked in.
manifests="${1:-}"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
kernel_version="$(cat "$here/../kernel/VERSION")"
k3s_version="$(cat "$here/../k3s/VERSION")"
xtables_version="$(cat "$here/../xtables/VERSION")"
kdist="$here/../kernel/dist/$kernel_version"
release="$(cat "$kdist/release")"

root="$here/dist/root"
rm -rf "$here/dist"
mkdir -p "$root/etc/ssl/certs" "$root/bin" "$root/sbin"

cp -r "$here/etc" "$root/"
cp "$here/../init/dist/liken" "$root/liken"
cp "$here/../k3s/dist/$k3s_version/k3s" "$root/bin/k3s"

# The deployment's manifests, staged at the paths init reads. Copied
# file by file rather than as a tree, so what the image can carry is
# explicit: one cluster document, one manifest per machine.
if [[ -n "$manifests" ]]; then
    if [[ -f "$manifests/cluster.yaml" ]]; then
        cp "$manifests/cluster.yaml" "$root/etc/liken/cluster.yaml"
    fi
    if [[ -d "$manifests/machines" ]]; then
        mkdir -p "$root/etc/liken/machines"
        cp "$manifests"/machines/*.yaml "$root/etc/liken/machines/"
    fi
fi

# The netfilter userspace: one real static binary, then a symlink per
# tool name: the multi-call binary reads argv[0] to know which tool to
# be. Only the legacy variant ships, matching the iptable_* kernel
# modules in modules.conf.
cp "$here/../xtables/dist/$xtables_version/bin/xtables-legacy-multi" "$root/sbin/"
for tool in iptables iptables-save iptables-restore \
            ip6tables ip6tables-save ip6tables-restore; do
    ln -s xtables-legacy-multi "$root/sbin/$tool"
done

# The filesystem maker, for the disks init claims.
e2fsprogs_version="$(cat "$here/../e2fsprogs/VERSION")"
cp "$here/../e2fsprogs/dist/$e2fsprogs_version/mke2fs" "$root/sbin/mke2fs"

# The pre-generated certificate authorities, placed exactly where k3s
# looks before generating its own.
mkdir -p "$root/var/lib/rancher/k3s/server"
cp -r "$here/../identity/dist/tls" "$root/var/lib/rancher/k3s/server/tls"

# The join token, minted alongside the CAs (identity/mint.sh explains
# the format). It lives under /etc/liken rather than k3s's data
# directory because the clusterState filesystem mounts over the
# latter: a boot input has to sit where no disk will shadow it. Init
# hands k3s the path (token-file), never the value.
cp "$here/../identity/dist/token" "$root/etc/liken/token"
chmod 600 "$root/etc/liken/token"

# The Machine API and its operator, delivered the Kubernetes way: the
# manifests go where k3s auto-applies them, the operator's image goes
# where k3s auto-imports it. The LIKEN_VERSION substitution pins the
# DaemonSet to exactly the image version this build ships alongside it.
liken_version="$(cat "$here/../VERSION")"
mkdir -p "$root/var/lib/rancher/k3s/server/manifests"
for manifest in "$here"/../operator/manifests/*.yaml; do
    sed "s/LIKEN_VERSION/$liken_version/g" "$manifest" \
        >"$root/var/lib/rancher/k3s/server/manifests/$(basename "$manifest")"
done
mkdir -p "$root/var/lib/rancher/k3s/agent/images"
cp "$here/../operator/dist/liken-operator-image.tar" \
   "$root/var/lib/rancher/k3s/agent/images/liken-operator.tar"

# The machine's trust store, vendored by the trust domain (where these
# roots come from is explained in trust/fetch.sh). The staged name is
# the conventional path Go's crypto/x509 and most TLS stacks probe.
trust_version="$(cat "$here/../trust/VERSION")"
cp "$here/../trust/dist/$trust_version/cacert.pem" \
   "$root/etc/ssl/certs/ca-certificates.crt"

# The image carries only the modules the machine will load (the list
# in etc/liken/modules.conf) plus everything they depend on. The
# host's modprobe resolves each name against the vendored kernel's
# depmod index
# (--show-depends prints one "insmod <path>" line per file, dependencies
# first) without loading anything anywhere.
mkdir -p "$root/lib/modules/$release"
while IFS= read -r name; do
    [[ -z "$name" || "$name" == \#* ]] && continue
    modprobe -d "$kdist" -S "$release" --show-depends "$name"
done <"$here/etc/liken/modules.conf" |
    awk '$1 == "insmod" { print $2 }' |
    sort -u |
    while IFS= read -r file; do
        rel="${file#"$kdist"/lib/modules/"$release"/}"
        mkdir -p "$root/lib/modules/$release/$(dirname "$rel")"
        cp "$file" "$root/lib/modules/$release/$rel"
    done

# depmod indexes what actually shipped, so init's dependency resolution
# (which reads modules.dep) agrees exactly with the files present.
# modules.builtin tells depmod which names live inside vmlinuz itself;
# modules.order settles ambiguity when two modules claim one alias.
cp "$kdist/lib/modules/$release/modules.builtin" \
   "$kdist/lib/modules/$release/modules.builtin.modinfo" \
   "$kdist/lib/modules/$release/modules.order" \
   "$root/lib/modules/$release/"
depmod --basedir "$root" "$release"

# cpio, flag by flag: -o creates an archive from filenames on stdin
# (the archive's contents are an explicit, reviewable stream); -H newc
# is the one format the kernel's unpacker accepts; -R +0:+0 makes root
# own everything, whoever ran the build.
(cd "$root" && find . | cpio --quiet -o -H newc -R +0:+0) >"$here/dist/liken.cpio"

echo "image for kernel $release, k3s $k3s_version:"
du -sh "$here/dist/liken.cpio"
